### ISSUE TITLE
Faille de sécurité potentielle

### ISSUE THREAD

**Issue by enzolhtt** [LaDetox87/Blog#2]
Vous n'avez pas restreint l'accès au /admin aux utilisateurs qui ont le grade Admin,

de ce fait, tout le monde peut se connecter aux crud réservés aux admins.

**Comment by LaDetox87** [comment]
C'est corrigé, la route /admin est maintenant restreinte au utilisateurs ayants le rôle admin.

**Comment by LaDetox87** [comment]
C'est corrigé, la route /admin est maintenant restreinte au utilisateurs ayants le rôle admin.
